version: "2"

services:
  satis:
    image: blackmorth/docker-satis:${IMAGE_VERSION}
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: satis
    hostname: satis
    networks:
      - webproxy
    volumes:
      - "~/.composer:/tmp/.composer"
      - "~/.ssh/id_rsa:/var/tmp/id"
      - "./config:/satisfy/config"
    environment:
      PRIVATE_REPO_DOMAIN_LIST: bitbucket.org github.com
      CRONTAB_FREQUENCY: "*/1 * * * *"
      VIRTUAL_HOST: ${VHOST}

networks:
  webproxy:
    external:
      name: ${PROXY_NETWORK}
